apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ingressmonitorcontroller.v2.0.11
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: EndpointMonitor is the Schema for the endpointmonitors API
      kind: EndpointMonitor
      name: endpointmonitors.endpointmonitor.stakater.com
      version: v1alpha1
  description: Placeholder description
  displayName: Ingress Monitor Controller
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          - extensions
          - route.openshift.io
          resources:
          - ingresses
          - routes
          - secrets
          verbs:
          - list
          - get
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          - services
          - configmaps
          - services/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
          - list
        - apiGroups:
          - apps
          resourceNames:
          - ingressmonitorcontroller
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - endpointmonitor.stakater.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ingressmonitorcontroller
      deployments:
      - name: ingressmonitorcontroller
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ingressmonitorcontroller
          strategy: {}
          template:
            metadata:
              labels:
                name: ingressmonitorcontroller
            spec:
              containers:
              - command:
                - IngressMonitorController
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ingressmonitorcontroller
                - name: CONFIG_SECRET_NAME
                  value: imc-config
                - name: LOG_LEVEL
                  value: info
                - name: LOG_FORMAT
                  value: text
                image: stakater/ingressmonitorcontroller:v2.0.11
                imagePullPolicy: Always
                name: ingressmonitorcontroller
                resources: {}
              serviceAccountName: ingressmonitorcontroller
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: ingressmonitorcontroller.v0.0.0
  version: 2.0.11
