apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingressmonitorcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ingressmonitorcontroller
  template:
    metadata:
      labels:
        name: ingressmonitorcontroller
    spec:
      serviceAccountName: ingressmonitorcontroller
      containers:
        - name: ingressmonitorcontroller
          image: stakater/ingressmonitorcontroller:v2.0.9
          command:
            - IngressMonitorController
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ingressmonitorcontroller"
            - name: CONFIG_SECRET_NAME
              value: imc-config
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: text
