apiVersion: v1
kind: Secret
metadata:
{{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "fullname" . }}-secret
{{- else }}
  name: {{ template "name" . }}-secret
{{- end }}
  annotations:
{{- if .Values.ingressMonitorController.secret.annotations }}
{{ toYaml .Values.ingressMonitorController.secret.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.ingressMonitorController.secret.labels }}
{{ toYaml .Values.ingressMonitorController.secret.labels | indent 4 }}
{{- end }}
{{- if .Values.ingressMonitorController.matchLabels }}
{{ toYaml .Values.ingressMonitorController.matchLabels | indent 4 }}
{{- end }}
stringData:
  config.yaml: |-
    providers:
    {{- range .Values.ingressMonitorController.providers }}
    - name: {{ .name }}
      apiKey: {{ .apiKey }}
      apiURL: {{ .apiURL }}
      username: {{ .username | default "null" }}
      password: {{ .password | default "null" }}
      alertContacts: {{ .alertContacts }}
    {{- end }}
    enableMonitorDeletion: {{ .Values.ingressMonitorController.enableMonitorDeletion }}
    monitorNameTemplate: "{{ .Values.ingressMonitorController.monitorNameTemplate }}"